-- Локалізація: підтримка вибору мови в налаштуваннях
-- AutoSellGrey_GetLocale(override) - override = "" або nil = мова гри
-- AutoSellGrey_LocaleList - список мов для dropdown {{code, displayName}, ...}

AutoSellGrey_Locales = {}

-- enUS (fallback)
AutoSellGrey_Locales["enUS"] = {
    LANG_NAME = "English",
    TITLE = "AutoSellGrey Settings",
    ENABLED_TEXT = "Enable Auto Sell Grey Items",
    DISABLED_TEXT = "Auto Sell Grey Items is disabled.",
    SELL_SUMMARY = "Sold %d grey items for: ",
    NO_ITEMS = "No grey items to sell.",
    SELL_LIMIT_REACHED = "Sell limit reached: only %d items sold to preserve buyback list.",
    LIMIT_SELL_TEXT = "Limit selling to %d items per vendor visit",
    MAX_ITEMS_LABEL = "Max items (1–48):",
    LIMIT_ENABLED = "Enabled sell limit.",
    LIMIT_DISABLED = "Disabled sell limit.",
    SILENT_MODE_TEXT = "Silent Mode (hide chat messages)",
    SHOW_SUMMARY_TEXT = "Show summary after selling",
    MINIMAP_BUTTON_TEXT = "Show minimap button",
    LANGUAGE_TEXT = "Addon language",
    SLASH_HELP_HEADER = "AutoSellGrey commands:",
    SLASH_HELP_ON = "  /asg on - enable auto sell",
    SLASH_HELP_OFF = "  /asg off - disable auto sell",
    SLASH_HELP_LIMIT = "  /asg limit - toggle sell limit",
    SLASH_HELP_MINIMAP = "  /asg minimap - toggle minimap icon",
    SLASH_HELP_SETTINGS = "  /asg settings - open settings",
    SLASH_HELP_STATUS = "  /asg status - show current settings",
    SLASH_HELP_SILENT = "  /asg silent - toggle silent mode",
    SLASH_HELP_SUMMARY = "  /asg summary - toggle post-sell summary",
    SLASH_HELP_BAGS = "  /asg bags - grey items in bags (count & vendor value)",
    SILENT_ENABLED_MSG = "Silent mode enabled.",
    SILENT_DISABLED_MSG = "Silent mode disabled.",
    SUMMARY_ENABLED_MSG = "Sell summary enabled.",
    SUMMARY_DISABLED_MSG = "Sell summary disabled.",
    BAGS_GREY_NONE = "No grey items in bags.",
    BAGS_GREY_HEADER = "Grey items in bags: %d. Vendor value: ",
    TOOLTIP_GREY_IN_BAGS = "Grey in bags: %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "No grey items in bags.",
    DEFAULT_LANGUAGE_OPTION = "Default (Game)",
    STATUS_TITLE = "AutoSellGrey status:",
    STATUS_LINE_AUTOSELL = "  Auto-sell: %s",
    STATUS_LINE_LIMIT = "  Per-visit sell limit: %s (%d items max)",
    STATUS_LINE_MINIMAP = "  Minimap button: %s",
    STATUS_LINE_SUMMARY = "  Show sell summary: %s",
    STATUS_LINE_SILENT = "  Silent mode: %s",
    WORD_ON = "On",
    WORD_OFF = "Off",
    WORD_YES = "Yes",
    WORD_NO = "No",
    TOOLTIP_LEFT_CLICK = "Left-Click - open settings",
    TOOLTIP_RIGHT_CLICK = "Right-Click - toggle On/Off",
    TOOLTIP_DRAG = "Drag to reposition",
    TOOLTIP_AUTOSELL = "Auto-sell: %s",
}

-- ukUA
AutoSellGrey_Locales["ukUA"] = {
    LANG_NAME = "Українська",
    TITLE = "Налаштування AutoSellGrey",
    ENABLED_TEXT = "Увімкнути автопродаж сірого",
    DISABLED_TEXT = "Автопродаж сірого вимкнено.",
    SELL_SUMMARY = "Продано %d сірих предметів на суму: ",
    NO_ITEMS = "Немає сірих предметів для продажу.",
    SELL_LIMIT_REACHED = "Досягнуто ліміт: продано лише %d предметів для збереження списку викупу.",
    LIMIT_SELL_TEXT = "Обмежити продаж до %d предметів за візит до торговця",
    MAX_ITEMS_LABEL = "Макс. предметів (1–48):",
    LIMIT_ENABLED = "Ліміт продажу увімкнено.",
    LIMIT_DISABLED = "Ліміт продажу вимкнено.",
    SILENT_MODE_TEXT = "Беззвучний режим (приховати повідомлення)",
    SHOW_SUMMARY_TEXT = "Показувати підсумок після продажу",
    MINIMAP_BUTTON_TEXT = "Показувати кнопку на мінімапі",
    LANGUAGE_TEXT = "Мова аддона",
    SLASH_HELP_HEADER = "AutoSellGrey команди:",
    SLASH_HELP_ON = "  /asg on - увімкнути автопродаж",
    SLASH_HELP_OFF = "  /asg off - вимкнути автопродаж",
    SLASH_HELP_LIMIT = "  /asg limit - перемкнути ліміт продажу",
    SLASH_HELP_MINIMAP = "  /asg minimap - сховати/показати іконку",
    SLASH_HELP_SETTINGS = "  /asg settings - відкрити налаштування",
    SLASH_HELP_STATUS = "  /asg status - показати поточні налаштування",
    SLASH_HELP_SILENT = "  /asg silent - беззвучний режим увімк/вимк",
    SLASH_HELP_SUMMARY = "  /asg summary - підсумок після продажу увімк/вимк",
    SLASH_HELP_BAGS = "  /asg bags - сірий у сумках (кількість і ціна у торговця)",
    SILENT_ENABLED_MSG = "Беззвучний режим увімкнено.",
    SILENT_DISABLED_MSG = "Беззвучний режим вимкнено.",
    SUMMARY_ENABLED_MSG = "Підсумок після продажу увімкнено.",
    SUMMARY_DISABLED_MSG = "Підсумок після продажу вимкнено.",
    BAGS_GREY_NONE = "Немає сірих предметів у сумках.",
    BAGS_GREY_HEADER = "Сірих у сумках: %d. Вартість у торговця: ",
    TOOLTIP_GREY_IN_BAGS = "Сірий у сумках: %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "Немає сірих предметів у сумках.",
    DEFAULT_LANGUAGE_OPTION = "За замовчуванням (мова клієнта)",
    STATUS_TITLE = "Стан AutoSellGrey:",
    STATUS_LINE_AUTOSELL = "  Автопродаж: %s",
    STATUS_LINE_LIMIT = "  Ліміт за візит: %s (макс. %d предметів)",
    STATUS_LINE_MINIMAP = "  Кнопка на мінімапі: %s",
    STATUS_LINE_SUMMARY = "  Підсумок після продажу: %s",
    STATUS_LINE_SILENT = "  Беззвучний режим: %s",
    WORD_ON = "Увімк.",
    WORD_OFF = "Вимк.",
    WORD_YES = "Так",
    WORD_NO = "Ні",
    TOOLTIP_LEFT_CLICK = "Лівою кнопкою - відкрити налаштування",
    TOOLTIP_RIGHT_CLICK = "Правою кнопкою - ввімк/вимк",
    TOOLTIP_DRAG = "Перетягніть для зміни позиції",
    TOOLTIP_AUTOSELL = "Автопродаж: %s",
}

-- ruRU
AutoSellGrey_Locales["ruRU"] = {
    LANG_NAME = "Русский",
    TITLE = "Настройки AutoSellGrey",
    ENABLED_TEXT = "Включить автопродаж серых предметов",
    DISABLED_TEXT = "Автопродажа серых предметов отключена.",
    SELL_SUMMARY = "Продано %d серых предметов на сумму: ",
    NO_ITEMS = "Нет серых предметов для продажи.",
    SELL_LIMIT_REACHED = "Достигнут лимит: продано только %d предметов для сохранения списка выкупа.",
    LIMIT_SELL_TEXT = "Ограничить продажу до %d предметов за визит к торговцу",
    MAX_ITEMS_LABEL = "Макс. предметов (1–48):",
    LIMIT_ENABLED = "Лимит продажи включён.",
    LIMIT_DISABLED = "Лимит продажи отключён.",
    SILENT_MODE_TEXT = "Тихий режим (скрыть сообщения)",
    SHOW_SUMMARY_TEXT = "Показывать итог после продажи",
    MINIMAP_BUTTON_TEXT = "Показывать кнопку на миникарте",
    LANGUAGE_TEXT = "Язык аддона",
    SLASH_HELP_HEADER = "Команды AutoSellGrey:",
    SLASH_HELP_ON = "  /asg on - включить автопродажу",
    SLASH_HELP_OFF = "  /asg off - отключить автопродажу",
    SLASH_HELP_LIMIT = "  /asg limit - переключить лимит продажи",
    SLASH_HELP_MINIMAP = "  /asg minimap - показать/скрыть иконку",
    SLASH_HELP_SETTINGS = "  /asg settings - открыть настройки",
    SLASH_HELP_STATUS = "  /asg status - показать текущие настройки",
    SLASH_HELP_SILENT = "  /asg silent - тихий режим вкл/выкл",
    SLASH_HELP_SUMMARY = "  /asg summary - итог после продажи вкл/выкл",
    SLASH_HELP_BAGS = "  /asg bags - серый в сумках (кол-во и цена скупщика)",
    SILENT_ENABLED_MSG = "Тихий режим включён.",
    SILENT_DISABLED_MSG = "Тихий режим выключен.",
    SUMMARY_ENABLED_MSG = "Итог после продажи включён.",
    SUMMARY_DISABLED_MSG = "Итог после продажи выключен.",
    BAGS_GREY_NONE = "Нет серых предметов в сумках.",
    BAGS_GREY_HEADER = "Серых в сумках: %d. Цена у торговца: ",
    TOOLTIP_GREY_IN_BAGS = "Серый в сумках: %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "Нет серых предметов в сумках.",
    DEFAULT_LANGUAGE_OPTION = "По умолчанию (язык клиента)",
    STATUS_TITLE = "Состояние AutoSellGrey:",
    STATUS_LINE_AUTOSELL = "  Автопродажа: %s",
    STATUS_LINE_LIMIT = "  Лимит за визит: %s (макс. %d предметов)",
    STATUS_LINE_MINIMAP = "  Кнопка на миникарте: %s",
    STATUS_LINE_SUMMARY = "  Итог после продажи: %s",
    STATUS_LINE_SILENT = "  Тихий режим: %s",
    WORD_ON = "Вкл.",
    WORD_OFF = "Выкл.",
    WORD_YES = "Да",
    WORD_NO = "Нет",
    TOOLTIP_LEFT_CLICK = "ЛКМ - открыть настройки",
    TOOLTIP_RIGHT_CLICK = "ПКМ - вкл/выкл",
    TOOLTIP_DRAG = "Перетащите для изменения позиции",
    TOOLTIP_AUTOSELL = "Автопродажа: %s",
}

-- deDE
AutoSellGrey_Locales["deDE"] = {
    LANG_NAME = "Deutsch",
    TITLE = "AutoSellGrey Einstellungen",
    ENABLED_TEXT = "Graue Gegenstände automatisch verkaufen",
    DISABLED_TEXT = "Automatischer Verkauf grauer Gegenstände deaktiviert.",
    SELL_SUMMARY = "%d graue Gegenstände verkauft für: ",
    NO_ITEMS = "Keine grauen Gegenstände zum Verkaufen.",
    SELL_LIMIT_REACHED = "Verkaufslimit erreicht: nur %d Gegenstände verkauft, um die Rückkaufliste zu erhalten.",
    LIMIT_SELL_TEXT = "Verkauf auf %d Gegenstände pro Händlerbesuch begrenzen",
    MAX_ITEMS_LABEL = "Maximum (1–48):",
    LIMIT_ENABLED = "Verkaufslimit aktiviert.",
    LIMIT_DISABLED = "Verkaufslimit deaktiviert.",
    SILENT_MODE_TEXT = "Stiller Modus (Chat-Nachrichten ausblenden)",
    SHOW_SUMMARY_TEXT = "Zusammenfassung nach dem Verkauf anzeigen",
    MINIMAP_BUTTON_TEXT = "Minikarten-Button anzeigen",
    LANGUAGE_TEXT = "Addon-Sprache",
    SLASH_HELP_HEADER = "AutoSellGrey Befehle:",
    SLASH_HELP_ON = "  /asg on - Autoverkauf aktivieren",
    SLASH_HELP_OFF = "  /asg off - Autoverkauf deaktivieren",
    SLASH_HELP_LIMIT = "  /asg limit - Verkaufslimit umschalten",
    SLASH_HELP_MINIMAP = "  /asg minimap - Minikarten-Icon ein/aus",
    SLASH_HELP_SETTINGS = "  /asg settings - Einstellungen öffnen",
    SLASH_HELP_STATUS = "  /asg status - aktuelle Einstellungen anzeigen",
    SLASH_HELP_SILENT = "  /asg silent - stillen Modus umschalten",
    SLASH_HELP_SUMMARY = "  /asg summary - Verkaufszusammenfassung umschalten",
    SLASH_HELP_BAGS = "  /asg bags - graue Items in Taschen (Anzahl & Händlerwert)",
    SILENT_ENABLED_MSG = "Stiller Modus aktiviert.",
    SILENT_DISABLED_MSG = "Stiller Modus deaktiviert.",
    SUMMARY_ENABLED_MSG = "Verkaufszusammenfassung aktiviert.",
    SUMMARY_DISABLED_MSG = "Verkaufszusammenfassung deaktiviert.",
    BAGS_GREY_NONE = "Keine grauen Gegenstände in den Taschen.",
    BAGS_GREY_HEADER = "Graue Gegenstände in Taschen: %d. Händlerwert: ",
    TOOLTIP_GREY_IN_BAGS = "Grau in Taschen: %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "Keine grauen Gegenstände in den Taschen.",
    DEFAULT_LANGUAGE_OPTION = "Standard (Spielsprache)",
    STATUS_TITLE = "AutoSellGrey Status:",
    STATUS_LINE_AUTOSELL = "  Autoverkauf: %s",
    STATUS_LINE_LIMIT = "  Verkaufslimit pro Besuch: %s (max. %d Gegenstände)",
    STATUS_LINE_MINIMAP = "  Minikarten-Button: %s",
    STATUS_LINE_SUMMARY = "  Verkaufszusammenfassung: %s",
    STATUS_LINE_SILENT = "  Stiller Modus: %s",
    WORD_ON = "An",
    WORD_OFF = "Aus",
    WORD_YES = "Ja",
    WORD_NO = "Nein",
    TOOLTIP_LEFT_CLICK = "Linksklick - Einstellungen öffnen",
    TOOLTIP_RIGHT_CLICK = "Rechtsklick - Ein/Aus",
    TOOLTIP_DRAG = "Ziehen zum Verschieben",
    TOOLTIP_AUTOSELL = "Autoverkauf: %s",
}

-- frFR
AutoSellGrey_Locales["frFR"] = {
    LANG_NAME = "Français",
    TITLE = "Paramètres AutoSellGrey",
    ENABLED_TEXT = "Activer la vente automatique des objets gris",
    DISABLED_TEXT = "Vente automatique des objets gris désactivée.",
    SELL_SUMMARY = "%d objets gris vendus pour : ",
    NO_ITEMS = "Aucun objet gris à vendre.",
    SELL_LIMIT_REACHED = "Limite atteinte : seulement %d objets vendus pour préserver la liste de rachat.",
    LIMIT_SELL_TEXT = "Limiter la vente à %d objets par visite chez le marchand",
    MAX_ITEMS_LABEL = "Maximum (1–48) :",
    LIMIT_ENABLED = "Limite de vente activée.",
    LIMIT_DISABLED = "Limite de vente désactivée.",
    SILENT_MODE_TEXT = "Mode silencieux (masquer les messages)",
    SHOW_SUMMARY_TEXT = "Afficher le résumé après la vente",
    MINIMAP_BUTTON_TEXT = "Afficher le bouton sur la minicarte",
    LANGUAGE_TEXT = "Langue de l'addon",
    SLASH_HELP_HEADER = "Commandes AutoSellGrey :",
    SLASH_HELP_ON = "  /asg on - activer la vente auto",
    SLASH_HELP_OFF = "  /asg off - désactiver la vente auto",
    SLASH_HELP_LIMIT = "  /asg limit - basculer la limite",
    SLASH_HELP_MINIMAP = "  /asg minimap - afficher/masquer l'icône",
    SLASH_HELP_SETTINGS = "  /asg settings - ouvrir les paramètres",
    SLASH_HELP_STATUS = "  /asg status - afficher les paramètres actuels",
    SLASH_HELP_SILENT = "  /asg silent - mode silencieux on/off",
    SLASH_HELP_SUMMARY = "  /asg summary - résumé après vente on/off",
    SLASH_HELP_BAGS = "  /asg bags - objets gris en sacs (nombre & valeur marchand)",
    SILENT_ENABLED_MSG = "Mode silencieux activé.",
    SILENT_DISABLED_MSG = "Mode silencieux désactivé.",
    SUMMARY_ENABLED_MSG = "Résumé après vente activé.",
    SUMMARY_DISABLED_MSG = "Résumé après vente désactivé.",
    BAGS_GREY_NONE = "Aucun objet gris dans les sacs.",
    BAGS_GREY_HEADER = "Objets gris en sacs : %d. Valeur marchand : ",
    TOOLTIP_GREY_IN_BAGS = "Gris en sacs : %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "Aucun objet gris dans les sacs.",
    DEFAULT_LANGUAGE_OPTION = "Par défaut (langue du jeu)",
    STATUS_TITLE = "État AutoSellGrey :",
    STATUS_LINE_AUTOSELL = "  Vente auto : %s",
    STATUS_LINE_LIMIT = "  Limite par visite : %s (%d objets max)",
    STATUS_LINE_MINIMAP = "  Bouton minicarte : %s",
    STATUS_LINE_SUMMARY = "  Résumé après vente : %s",
    STATUS_LINE_SILENT = "  Mode silencieux : %s",
    WORD_ON = "Activé",
    WORD_OFF = "Désactivé",
    WORD_YES = "Oui",
    WORD_NO = "Non",
    TOOLTIP_LEFT_CLICK = "Clic gauche - ouvrir les paramètres",
    TOOLTIP_RIGHT_CLICK = "Clic droit - activer/désactiver",
    TOOLTIP_DRAG = "Glisser pour déplacer",
    TOOLTIP_AUTOSELL = "Vente auto : %s",
}

-- esES / esMX
local esLocale = {
    LANG_NAME = "Español",
    TITLE = "Configuración AutoSellGrey",
    ENABLED_TEXT = "Activar venta automática de objetos grises",
    DISABLED_TEXT = "Venta automática de objetos grises desactivada.",
    SELL_SUMMARY = "Vendidos %d objetos grises por: ",
    NO_ITEMS = "No hay objetos grises para vender.",
    SELL_LIMIT_REACHED = "Límite alcanzado: solo %d objetos vendidos para preservar la lista de recompras.",
    LIMIT_SELL_TEXT = "Limitar venta a %d objetos por visita al vendedor",
    MAX_ITEMS_LABEL = "Máximo (1–48):",
    LIMIT_ENABLED = "Límite de venta activado.",
    LIMIT_DISABLED = "Límite de venta desactivado.",
    SILENT_MODE_TEXT = "Modo silencioso (ocultar mensajes)",
    SHOW_SUMMARY_TEXT = "Mostrar resumen después de vender",
    MINIMAP_BUTTON_TEXT = "Mostrar botón en minimapa",
    LANGUAGE_TEXT = "Idioma del addon",
    SLASH_HELP_HEADER = "Comandos AutoSellGrey:",
    SLASH_HELP_ON = "  /asg on - activar venta auto",
    SLASH_HELP_OFF = "  /asg off - desactivar venta auto",
    SLASH_HELP_LIMIT = "  /asg limit - alternar límite",
    SLASH_HELP_MINIMAP = "  /asg minimap - mostrar/ocultar icono",
    SLASH_HELP_SETTINGS = "  /asg settings - abrir configuración",
    SLASH_HELP_STATUS = "  /asg status - mostrar ajustes actuales",
    SLASH_HELP_SILENT = "  /asg silent - modo silencioso sí/no",
    SLASH_HELP_SUMMARY = "  /asg summary - resumen tras vender sí/no",
    SLASH_HELP_BAGS = "  /asg bags - grises en las bolsas (cantidad y valor vendedor)",
    SILENT_ENABLED_MSG = "Modo silencioso activado.",
    SILENT_DISABLED_MSG = "Modo silencioso desactivado.",
    SUMMARY_ENABLED_MSG = "Resumen tras vender activado.",
    SUMMARY_DISABLED_MSG = "Resumen tras vender desactivado.",
    BAGS_GREY_NONE = "No hay objetos grises en las bolsas.",
    BAGS_GREY_HEADER = "Objetos grises en bolsas: %d. Valor con el vendedor: ",
    TOOLTIP_GREY_IN_BAGS = "Gris en bolsas: %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "No hay objetos grises en las bolsas.",
    DEFAULT_LANGUAGE_OPTION = "Predeterminado (idioma del juego)",
    STATUS_TITLE = "Estado de AutoSellGrey:",
    STATUS_LINE_AUTOSELL = "  Venta automática: %s",
    STATUS_LINE_LIMIT = "  Límite por visita: %s (máx. %d objetos)",
    STATUS_LINE_MINIMAP = "  Botón del minimapa: %s",
    STATUS_LINE_SUMMARY = "  Resumen tras vender: %s",
    STATUS_LINE_SILENT = "  Modo silencioso: %s",
    WORD_ON = "Activado",
    WORD_OFF = "Desactivado",
    WORD_YES = "Sí",
    WORD_NO = "No",
    TOOLTIP_LEFT_CLICK = "Clic izquierdo - abrir configuración",
    TOOLTIP_RIGHT_CLICK = "Clic derecho - activar/desactivar",
    TOOLTIP_DRAG = "Arrastrar para mover",
    TOOLTIP_AUTOSELL = "Venta automática: %s",
}
AutoSellGrey_Locales["esES"] = esLocale
AutoSellGrey_Locales["esMX"] = esLocale

-- ptBR
AutoSellGrey_Locales["ptBR"] = {
    LANG_NAME = "Português",
    TITLE = "Configurações AutoSellGrey",
    ENABLED_TEXT = "Ativar venda automática de itens cinza",
    DISABLED_TEXT = "Venda automática de itens cinza desativada.",
    SELL_SUMMARY = "Vendidos %d itens cinza por: ",
    NO_ITEMS = "Nenhum item cinza para vender.",
    SELL_LIMIT_REACHED = "Limite atingido: apenas %d itens vendidos para preservar a lista de recompra.",
    LIMIT_SELL_TEXT = "Limitar venda a %d itens por visita ao mercador",
    MAX_ITEMS_LABEL = "Máximo (1–48):",
    LIMIT_ENABLED = "Limite de venda ativado.",
    LIMIT_DISABLED = "Limite de venda desativado.",
    SILENT_MODE_TEXT = "Modo silencioso (ocultar mensagens)",
    SHOW_SUMMARY_TEXT = "Mostrar resumo após vender",
    MINIMAP_BUTTON_TEXT = "Mostrar botão no minimapa",
    LANGUAGE_TEXT = "Idioma do addon",
    SLASH_HELP_HEADER = "Comandos AutoSellGrey:",
    SLASH_HELP_ON = "  /asg on - ativar venda auto",
    SLASH_HELP_OFF = "  /asg off - desativar venda auto",
    SLASH_HELP_LIMIT = "  /asg limit - alternar limite",
    SLASH_HELP_MINIMAP = "  /asg minimap - mostrar/ocultar ícone",
    SLASH_HELP_SETTINGS = "  /asg settings - abrir configurações",
    SLASH_HELP_STATUS = "  /asg status - mostrar configurações atuais",
    SLASH_HELP_SILENT = "  /asg silent - modo silencioso lig/desl",
    SLASH_HELP_SUMMARY = "  /asg summary - resumo após vender lig/desl",
    SLASH_HELP_BAGS = "  /asg bags - cinza nas bolsas (quantidade e valor no mercador)",
    SILENT_ENABLED_MSG = "Modo silencioso ativado.",
    SILENT_DISABLED_MSG = "Modo silencioso desativado.",
    SUMMARY_ENABLED_MSG = "Resumo após vender ativado.",
    SUMMARY_DISABLED_MSG = "Resumo após vender desativado.",
    BAGS_GREY_NONE = "Nenhum item cinza nas bolsas.",
    BAGS_GREY_HEADER = "Itens cinza nas bolsas: %d. Valor no mercador: ",
    TOOLTIP_GREY_IN_BAGS = "Cinza nas bolsas: %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "Nenhum item cinza nas bolsas.",
    DEFAULT_LANGUAGE_OPTION = "Padrão (idioma do jogo)",
    STATUS_TITLE = "Estado do AutoSellGrey:",
    STATUS_LINE_AUTOSELL = "  Venda automática: %s",
    STATUS_LINE_LIMIT = "  Limite por visita: %s (máx. %d itens)",
    STATUS_LINE_MINIMAP = "  Botão no minimapa: %s",
    STATUS_LINE_SUMMARY = "  Resumo após vender: %s",
    STATUS_LINE_SILENT = "  Modo silencioso: %s",
    WORD_ON = "Ligado",
    WORD_OFF = "Desligado",
    WORD_YES = "Sim",
    WORD_NO = "Não",
    TOOLTIP_LEFT_CLICK = "Clique esquerdo - abrir configurações",
    TOOLTIP_RIGHT_CLICK = "Clique direito - ativar/desativar",
    TOOLTIP_DRAG = "Arrastar para mover",
    TOOLTIP_AUTOSELL = "Venda automática: %s",
}

-- itIT
AutoSellGrey_Locales["itIT"] = {
    LANG_NAME = "Italiano",
    TITLE = "Impostazioni AutoSellGrey",
    ENABLED_TEXT = "Abilita vendita automatica oggetti grigi",
    DISABLED_TEXT = "Vendita automatica oggetti grigi disattivata.",
    SELL_SUMMARY = "Venduti %d oggetti grigi per: ",
    NO_ITEMS = "Nessun oggetto grigio da vendere.",
    SELL_LIMIT_REACHED = "Limite raggiunto: solo %d oggetti venduti per preservare la lista di ricompra.",
    LIMIT_SELL_TEXT = "Limitare la vendita a %d oggetti per visita al mercante",
    MAX_ITEMS_LABEL = "Massimo (1–48):",
    LIMIT_ENABLED = "Limite di vendita attivato.",
    LIMIT_DISABLED = "Limite di vendita disattivato.",
    SILENT_MODE_TEXT = "Modalità silenziosa (nascondi messaggi)",
    SHOW_SUMMARY_TEXT = "Mostra riepilogo dopo la vendita",
    MINIMAP_BUTTON_TEXT = "Mostra pulsante sulla minimappa",
    LANGUAGE_TEXT = "Lingua dell'addon",
    SLASH_HELP_HEADER = "Comandi AutoSellGrey:",
    SLASH_HELP_ON = "  /asg on - abilita vendita auto",
    SLASH_HELP_OFF = "  /asg off - disabilita vendita auto",
    SLASH_HELP_LIMIT = "  /asg limit - alterna limite vendita",
    SLASH_HELP_MINIMAP = "  /asg minimap - mostra/nascondi icona",
    SLASH_HELP_SETTINGS = "  /asg settings - apri impostazioni",
    SLASH_HELP_STATUS = "  /asg status - mostra impostazioni attuali",
    SLASH_HELP_SILENT = "  /asg silent - modalità silenziosa on/off",
    SLASH_HELP_SUMMARY = "  /asg summary - riepilogo dopo vendita on/off",
    SLASH_HELP_BAGS = "  /asg bags - oggetti grigi in borse (numero e valore mercante)",
    SILENT_ENABLED_MSG = "Modalità silenziosa attivata.",
    SILENT_DISABLED_MSG = "Modalità silenziosa disattivata.",
    SUMMARY_ENABLED_MSG = "Riepilogo dopo la vendita attivato.",
    SUMMARY_DISABLED_MSG = "Riepilogo dopo la vendita disattivato.",
    BAGS_GREY_NONE = "Nessun oggetto grigio nelle borse.",
    BAGS_GREY_HEADER = "Oggetti grigi nelle borse: %d. Valore mercante: ",
    TOOLTIP_GREY_IN_BAGS = "Grigio in borse: %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "Nessun oggetto grigio nelle borse.",
    DEFAULT_LANGUAGE_OPTION = "Predefinito (lingua del gioco)",
    STATUS_TITLE = "Stato AutoSellGrey:",
    STATUS_LINE_AUTOSELL = "  Vendita automatica: %s",
    STATUS_LINE_LIMIT = "  Limite per visita: %s (max %d oggetti)",
    STATUS_LINE_MINIMAP = "  Pulsante minimappa: %s",
    STATUS_LINE_SUMMARY = "  Riepilogo dopo la vendita: %s",
    STATUS_LINE_SILENT = "  Modalità silenziosa: %s",
    WORD_ON = "Attivo",
    WORD_OFF = "Disattivo",
    WORD_YES = "Sì",
    WORD_NO = "No",
    TOOLTIP_LEFT_CLICK = "Click sinistro - apri impostazioni",
    TOOLTIP_RIGHT_CLICK = "Click destro - attiva/disattiva",
    TOOLTIP_DRAG = "Trascina per spostare",
    TOOLTIP_AUTOSELL = "Vendita automatica: %s",
}

-- zhCN
AutoSellGrey_Locales["zhCN"] = {
    LANG_NAME = "简体中文",
    TITLE = "AutoSellGrey 设置",
    ENABLED_TEXT = "启用自动出售灰色物品",
    DISABLED_TEXT = "自动出售灰色物品已禁用。",
    SELL_SUMMARY = "已出售 %d 件灰色物品，共获得：",
    NO_ITEMS = "没有可出售的灰色物品。",
    SELL_LIMIT_REACHED = "已达到出售上限：仅出售%d件物品以保留回购列表。",
    LIMIT_SELL_TEXT = "每次拜访商人最多出售%d件物品",
    MAX_ITEMS_LABEL = "上限（1–48）：",
    LIMIT_ENABLED = "已启用出售限制。",
    LIMIT_DISABLED = "已禁用出售限制。",
    SILENT_MODE_TEXT = "静默模式（隐藏聊天消息）",
    SHOW_SUMMARY_TEXT = "出售后显示摘要",
    MINIMAP_BUTTON_TEXT = "显示小地图按钮",
    LANGUAGE_TEXT = "插件语言",
    SLASH_HELP_HEADER = "AutoSellGrey 命令：",
    SLASH_HELP_ON = "  /asg on - 启用自动出售",
    SLASH_HELP_OFF = "  /asg off - 禁用自动出售",
    SLASH_HELP_LIMIT = "  /asg limit - 切换出售限制",
    SLASH_HELP_MINIMAP = "  /asg minimap - 显示/隐藏图标",
    SLASH_HELP_SETTINGS = "  /asg settings - 打开设置",
    SLASH_HELP_STATUS = "  /asg status - 显示当前设置",
    SLASH_HELP_SILENT = "  /asg silent - 切换静默模式",
    SLASH_HELP_SUMMARY = "  /asg summary - 切换出售后摘要",
    SLASH_HELP_BAGS = "  /asg bags - 背包中灰色物品（数量与商人价值）",
    SILENT_ENABLED_MSG = "已启用静默模式。",
    SILENT_DISABLED_MSG = "已禁用静默模式。",
    SUMMARY_ENABLED_MSG = "已启用出售后摘要。",
    SUMMARY_DISABLED_MSG = "已禁用出售后摘要。",
    BAGS_GREY_NONE = "背包中没有灰色物品。",
    BAGS_GREY_HEADER = "背包中灰色物品：%d。商人价值：",
    TOOLTIP_GREY_IN_BAGS = "背包灰色：%d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "背包中没有灰色物品。",
    DEFAULT_LANGUAGE_OPTION = "默认（游戏客户端语言）",
    STATUS_TITLE = "AutoSellGrey 状态：",
    STATUS_LINE_AUTOSELL = "  自动出售：%s",
    STATUS_LINE_LIMIT = "  每次拜访限制：%s（最多 %d 件）",
    STATUS_LINE_MINIMAP = "  小地图按钮：%s",
    STATUS_LINE_SUMMARY = "  出售后显示摘要：%s",
    STATUS_LINE_SILENT = "  静默模式：%s",
    WORD_ON = "开",
    WORD_OFF = "关",
    WORD_YES = "是",
    WORD_NO = "否",
    TOOLTIP_LEFT_CLICK = "左键点击 - 打开设置",
    TOOLTIP_RIGHT_CLICK = "右键点击 - 开启/关闭",
    TOOLTIP_DRAG = "拖动可改变位置",
    TOOLTIP_AUTOSELL = "自动出售：%s",
}

-- zhTW
AutoSellGrey_Locales["zhTW"] = {
    LANG_NAME = "繁體中文",
    TITLE = "AutoSellGrey 設定",
    ENABLED_TEXT = "啟用自動出售灰色物品",
    DISABLED_TEXT = "自動出售灰色物品已停用。",
    SELL_SUMMARY = "已出售 %d 件灰色物品，共獲得：",
    NO_ITEMS = "沒有可出售的灰色物品。",
    SELL_LIMIT_REACHED = "已達出售上限：僅出售%d件物品以保留回購列表。",
    LIMIT_SELL_TEXT = "每次拜訪商人最多出售%d件物品",
    MAX_ITEMS_LABEL = "上限（1–48）：",
    LIMIT_ENABLED = "已啟用出售限制。",
    LIMIT_DISABLED = "已停用出售限制。",
    SILENT_MODE_TEXT = "靜默模式（隱藏聊天訊息）",
    SHOW_SUMMARY_TEXT = "出售後顯示摘要",
    MINIMAP_BUTTON_TEXT = "顯示小地圖按鈕",
    LANGUAGE_TEXT = "插件語言",
    SLASH_HELP_HEADER = "AutoSellGrey 指令：",
    SLASH_HELP_ON = "  /asg on - 啟用自動出售",
    SLASH_HELP_OFF = "  /asg off - 停用自動出售",
    SLASH_HELP_LIMIT = "  /asg limit - 切換出售限制",
    SLASH_HELP_MINIMAP = "  /asg minimap - 顯示/隱藏圖示",
    SLASH_HELP_SETTINGS = "  /asg settings - 開啟設定",
    SLASH_HELP_STATUS = "  /asg status - 顯示目前設定",
    SLASH_HELP_SILENT = "  /asg silent - 切換靜默模式",
    SLASH_HELP_SUMMARY = "  /asg summary - 切換出售後摘要",
    SLASH_HELP_BAGS = "  /asg bags - 背包中灰色物品（數量與商人價值）",
    SILENT_ENABLED_MSG = "已啟用靜默模式。",
    SILENT_DISABLED_MSG = "已停用靜默模式。",
    SUMMARY_ENABLED_MSG = "已啟用出售後摘要。",
    SUMMARY_DISABLED_MSG = "已停用出售後摘要。",
    BAGS_GREY_NONE = "背包中沒有灰色物品。",
    BAGS_GREY_HEADER = "背包中灰色物品：%d。商人價值：",
    TOOLTIP_GREY_IN_BAGS = "背包灰色：%d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "背包中沒有灰色物品。",
    DEFAULT_LANGUAGE_OPTION = "預設（遊戲用戶端語言）",
    STATUS_TITLE = "AutoSellGrey 狀態：",
    STATUS_LINE_AUTOSELL = "  自動出售：%s",
    STATUS_LINE_LIMIT = "  每次拜訪限制：%s（最多 %d 件）",
    STATUS_LINE_MINIMAP = "  小地圖按鈕：%s",
    STATUS_LINE_SUMMARY = "  出售後顯示摘要：%s",
    STATUS_LINE_SILENT = "  靜默模式：%s",
    WORD_ON = "開",
    WORD_OFF = "關",
    WORD_YES = "是",
    WORD_NO = "否",
    TOOLTIP_LEFT_CLICK = "左鍵點擊 - 開啟設定",
    TOOLTIP_RIGHT_CLICK = "右鍵點擊 - 開啟/關閉",
    TOOLTIP_DRAG = "拖曳可改變位置",
    TOOLTIP_AUTOSELL = "自動出售：%s",
}

-- koKR
AutoSellGrey_Locales["koKR"] = {
    LANG_NAME = "한국어",
    TITLE = "AutoSellGrey 설정",
    ENABLED_TEXT = "회색 아이템 자동 판매 사용",
    DISABLED_TEXT = "회색 아이템 자동 판매가 비활성화되었습니다.",
    SELL_SUMMARY = "회색 아이템 %d개 판매 금액: ",
    NO_ITEMS = "판매할 회색 아이템이 없습니다.",
    SELL_LIMIT_REACHED = "판매 한도 도달: 되사기 목록 유지를 위해 %d개만 판매됨.",
    LIMIT_SELL_TEXT = "상인 방문당 최대 %d개로 판매 제한",
    MAX_ITEMS_LABEL = "최대 (1–48):",
    LIMIT_ENABLED = "판매 제한 사용됨.",
    LIMIT_DISABLED = "판매 제한 해제됨.",
    SILENT_MODE_TEXT = "조용한 모드 (채팅 메시지 숨기기)",
    SHOW_SUMMARY_TEXT = "판매 후 요약 표시",
    MINIMAP_BUTTON_TEXT = "미니맵 버튼 표시",
    LANGUAGE_TEXT = "애드온 언어",
    SLASH_HELP_HEADER = "AutoSellGrey 명령:",
    SLASH_HELP_ON = "  /asg on - 자동 판매 사용",
    SLASH_HELP_OFF = "  /asg off - 자동 판매 비활성화",
    SLASH_HELP_LIMIT = "  /asg limit - 판매 제한 전환",
    SLASH_HELP_MINIMAP = "  /asg minimap - 아이콘 표시/숨기기",
    SLASH_HELP_SETTINGS = "  /asg settings - 설정 열기",
    SLASH_HELP_STATUS = "  /asg status - 현재 설정 표시",
    SLASH_HELP_SILENT = "  /asg silent - 조용한 모드 전환",
    SLASH_HELP_SUMMARY = "  /asg summary - 판매 후 요약 전환",
    SLASH_HELP_BAGS = "  /asg bags - 가방의 회색 아이템 (개수 및 상인 가격)",
    SILENT_ENABLED_MSG = "조용한 모드가 켜졌습니다.",
    SILENT_DISABLED_MSG = "조용한 모드가 꺼졌습니다.",
    SUMMARY_ENABLED_MSG = "판매 후 요약이 켜졌습니다.",
    SUMMARY_DISABLED_MSG = "판매 후 요약이 꺼졌습니다.",
    BAGS_GREY_NONE = "가방에 회색 아이템이 없습니다.",
    BAGS_GREY_HEADER = "가방의 회색 아이템: %d. 상인 가격: ",
    TOOLTIP_GREY_IN_BAGS = "가방 회색: %d — ",
    TOOLTIP_GREY_IN_BAGS_EMPTY = "가방에 회색 아이템이 없습니다.",
    DEFAULT_LANGUAGE_OPTION = "기본값 (게임 언어)",
    STATUS_TITLE = "AutoSellGrey 상태:",
    STATUS_LINE_AUTOSELL = "  자동 판매: %s",
    STATUS_LINE_LIMIT = "  방문당 판매 제한: %s (최대 %d개)",
    STATUS_LINE_MINIMAP = "  미니맵 버튼: %s",
    STATUS_LINE_SUMMARY = "  판매 후 요약: %s",
    STATUS_LINE_SILENT = "  조용한 모드: %s",
    WORD_ON = "켜짐",
    WORD_OFF = "꺼짐",
    WORD_YES = "예",
    WORD_NO = "아니오",
    TOOLTIP_LEFT_CLICK = "좌클릭 - 설정 열기",
    TOOLTIP_RIGHT_CLICK = "우클릭 - 켜기/끄기",
    TOOLTIP_DRAG = "드래그하여 이동",
    TOOLTIP_AUTOSELL = "자동 판매: %s",
}

-- Список мов для dropdown: {value, label}
-- value "" = мова гри (Default)
AutoSellGrey_LocaleList = {
    { value = "", label = "Default (Game)" },
    { value = "enUS", label = "English" },
    { value = "ukUA", label = "Українська" },
    { value = "ruRU", label = "Русский" },
    { value = "deDE", label = "Deutsch" },
    { value = "frFR", label = "Français" },
    { value = "esES", label = "Español" },
    { value = "ptBR", label = "Português" },
    { value = "itIT", label = "Italiano" },
    { value = "zhCN", label = "简体中文" },
    { value = "zhTW", label = "繁體中文" },
    { value = "koKR", label = "한국어" },
}

-- Якщо для коду клієнта немає окремого файлу — підставляємо найближчу підтримувану мову.
local localeFallback = {
    ptPT = "ptBR",
    enGB = "enUS",
}

function AutoSellGrey_GetLocale(override)
    local locale = (override and override ~= "") and override or GetLocale()
    local t = AutoSellGrey_Locales[locale]
    if not t then
        local fb = localeFallback[locale]
        if fb then
            t = AutoSellGrey_Locales[fb]
        end
    end
    return t or AutoSellGrey_Locales["enUS"]
end
