CasualTBCPrep.Themes = CasualTBCPrep.Themes or {}
CasualTBCPrep.Themes.DefaultThemeCode = "DEFAULT"

local themeData = {
	["DEFAULT"] = {
		colors = {
			white = 				{r=1, g=1, b=1, hex="|cFFFFFFFF"},
			black = 				{r=0, g=0, b=0, hex="|cFF000000"},

			notifyErrorStart=	    {r=0.929, g=0.427, b=0.176, hex="|cFFED6D2D"},
			notifyErrorText=		{r=0.890, g=0.125, b=0.125, hex="|cFFE32020"},
			notifyInfoStart=		{r=0.580, g=0.784, b=0.878, hex="|cFF94C8E0"},
			notifyInfoText=		    {r=0.820, g=0.902, b=0.831, hex="|cFFD1E6D4"},

			bad=					{r=1, g=0, b=0, hex="|cFFFF0000"},
			good=					{r=0, g=1, b=0, hex="|cFF00FF00"},
			warn=					{r=1, g=0.819, b=0, hex="|cFFFFD100"},
			auctionhouse=			{r=1, g=1, b=0, hex="|cFFFFFF00"},

			questCompleted=		    {r=0.95, g=0.09, b=0.11, hex="|cFFF2181C"},
			questAvailable=		    {r=0.357, g=0.741, b=0.667, hex="|cFF5BBDAA"},
			questReady=			    {r=0.02, g=0.99, b=0.03, hex="|cFF05FC08"},
			questReadyBanked=	    {r=0.51, g=0.76, b=0.38, hex="|cFF82C261"},
			questIgnored=			{r=0.55, g=0.50, b=0.65, hex="|cFF8C80A6"},
			questPickup=			{r=0.62, g=0.78, b=0.90, hex="|cFF9EC7E6"},

			tooltipLeftExp=		    {r=0.741, g=0.733, b=0.423, hex="|cFFBDBB6C"},
			tooltipLeftZone=		{r=0.741, g=0.733, b=0.423, hex="|cFFBDBB6C"},
			tooltipLeftCurrentStep= {r=0.741, g=0.733, b=0.423, hex="|cFFBDBB6C"},

			standoutText=		    {r=0.423, g=0.741, b=0.67, hex="|cFF6CBDAB"},
			manualText=				{r=0.86, g=0.85, b=0.75, hex="|cFFD8D9BF"},

			headerSpecial=		    {r=0.40, g=0.35, b=0.72, hex="|cFF6659B7"},
			headerSpecialHover=	    {r=0.60, g=0.55, b=0.92, hex="|cFF998CEB"},
			specialSelected=		{r=0.42, g=0.86, b=0.42, hex="|cFF6BDB6B"},
			specialNotSelected=	    {r=0.86, g=0.56, b=0.43, hex="|cFFDB8F6B"},

			currentStepProgress=	{r=1, g=1, b=0, hex="|cFFFFFF00"},
			currentStepArea=		{r=0.776, g=0.792, b=0.788, hex="|cFFC6CAC9"},
		}
	},
	["DISTINCT"] = {
		colors = {
			white = 				{r=1, g=1, b=1, hex="|cFFFFFFFF"},
			black = 				{r=0, g=0, b=0, hex="|cFF000000"},

			notifyErrorStart=	    {r=0.929, g=0.427, b=0.176, hex="|cFFED6D2D"},
			notifyErrorText=		{r=0.890, g=0.125, b=0.125, hex="|cFFE32020"},
			notifyInfoStart=		{r=0.580, g=0.784, b=0.878, hex="|cFF94C8E0"},
			notifyInfoText=		    {r=0.820, g=0.902, b=0.831, hex="|cFFD1E6D4"},

			bad=					{r=1, g=0, b=0, hex="|cFFFF0000"},
			good=					{r=0, g=1, b=0, hex="|cFF00FF00"},
			warn=					{r=1, g=0.819, b=0, hex="|cFFFFD100"},

			auctionhouse=			{r=1, g=1, b=0, hex="|cFFFFFF00"},

			questCompleted=		    {r=0.95, g=0.09, b=0.11, hex="|cFFF2181C"},
			questAvailable=		    {r=0.388, g=0.522, b=1, hex="|cFF6385FF"},
			questReady=			    {r=0., g=1, b=0, hex="|cFF00FF00"},
			questReadyBanked=	    {r=0.98, g=0.98, b=0.41, hex="|cFFfafc6a"},
			questIgnored=			{r=0.65, g=0.65, b=0.65, hex="|cFFA6A6A6"},
			questPickup=			{r=0.55, g=0.80, b=0.85, hex="|cFF8CD0D9"},

			tooltipLeftExp=		    {r=0.741, g=0.733, b=0.423, hex="|cFFBDBB6C"},
			tooltipLeftZone=		{r=0.741, g=0.733, b=0.423, hex="|cFFBDBB6C"},
			tooltipLeftCurrentStep= {r=0.741, g=0.733, b=0.423, hex="|cFFBDBB6C"},

			standoutText=		    {r=0.423, g=0.741, b=0.67, hex="|cFF6CBDAB"},
			manualText=				{r=0.86, g=0.85, b=0.75, hex="|cFFD8D9BF"},

			headerSpecial=		    {r=0.40, g=0.35, b=0.72, hex="|cFF6659B7"},
			headerSpecialHover=	    {r=0.60, g=0.55, b=0.92, hex="|cFF998CEB"},
			specialSelected=		{r=0.42, g=0.86, b=0.42, hex="|cFF6BDB6B"},
			specialNotSelected=	    {r=0.86, g=0.56, b=0.43, hex="|cFFDB8F6B"},

			currentStepProgress=	{r=1, g=1, b=0, hex="|cFFFFFF00"},
			currentStepArea=		{r=0.776, g=0.792, b=0.788, hex="|cFFC6CAC9"},
		}
	},
	["CB_DEUTE"] = { -- Generated by AI
		colors = {
			white = 				{r=1, g=1, b=1, hex="|cFFFFFFFF"},
			black = 				{r=0, g=0, b=0, hex="|cFF000000"},

			notifyErrorStart=		{r=0.929, g=0.427, b=0.176, hex="|cFFED6D2D"},
			notifyErrorText=		{r=0.890, g=0.125, b=0.125, hex="|cFFE32020"},
			notifyInfoStart=		{r=0.580, g=0.784, b=0.878, hex="|cFF94C8E0"},
			notifyInfoText=			{r=0.820, g=0.902, b=0.831, hex="|cFFD1E6D4"},

			-- Status: Blue/Yellow/White (avoid red/green confusion)
			bad=					{r=0.902, g=0.302, b=0.251, hex="|cFFE64D40"},
			good=					{r=0.204, g=0.596, b=0.859, hex="|cFF3498DB"},
			warn=					{r=1, g=0.843, b=0, hex="|cFFFFD700"},
			auctionhouse=			{r=1, g=0.843, b=0, hex="|cFFFFD700"},

			-- Quest states: use blue/orange spectrum
			questCompleted=			{r=0.584, g=0.647, b=0.651, hex="|cFF95A5A6"},
			questAvailable=			{r=0.902, g=0.486, b=0.133, hex="|cFFE67E22"},
			questReady=				{r=0.204, g=0.596, b=0.859, hex="|cFF3498DB"},
			questReadyBanked=		{r=0.400, g=0.710, b=0.902, hex="|cFF66B5E6"},
			questIgnored=			{r=0.55, g=0.55, b=0.65, hex="|cFF8C8CA6"},
			questPickup=			{r=0.45, g=0.70, b=0.90, hex="|cFF73B3E6"},

			-- Tooltip labels: warm tone
			tooltipLeftExp=			{r=0.953, g=0.612, b=0.071, hex="|cFFF39C12"},
			tooltipLeftZone=		{r=0.953, g=0.612, b=0.071, hex="|cFFF39C12"},
			tooltipLeftCurrentStep= {r=0.953, g=0.612, b=0.071, hex="|cFFF39C12"},

			-- Standout text: cool blue
			standoutText=			{r=0.204, g=0.596, b=0.859, hex="|cFF3498DB"},
			manualText=				{r=0.86, g=0.85, b=0.75, hex="|cFFD8D9BF"},

			headerSpecial=			{r=0.40, g=0.35, b=0.72, hex="|cFF6659B7"},
			headerSpecialHover=		{r=0.60, g=0.55, b=0.92, hex="|cFF998CEB"},
			specialSelected=		{r=0.42, g=0.86, b=0.42, hex="|cFF6BDB6B"},
			specialNotSelected=		{r=0.86, g=0.56, b=0.43, hex="|cFFDB8F6B"},

			-- Progress: orange and light
			currentStepProgress=	{r=0.953, g=0.612, b=0.071, hex="|cFFF39C12"},
			currentStepArea=		{r=0.925, g=0.941, b=0.945, hex="|cFFECF0F1"},
		}
	},
	["CB_TRITAN"] = { -- Generated by AI
		colors = {
			white = 				{r=1, g=1, b=1, hex="|cFFFFFFFF"},
			black = 				{r=0, g=0, b=0, hex="|cFF000000"},

			notifyErrorStart=		{r=0.929, g=0.427, b=0.176, hex="|cFFED6D2D"},
			notifyErrorText=		{r=0.890, g=0.125, b=0.125, hex="|cFFE32020"},
			notifyInfoStart=		{r=0.580, g=0.784, b=0.878, hex="|cFF94C8E0"},
			notifyInfoText=			{r=0.820, g=0.902, b=0.831, hex="|cFFD1E6D4"},

			-- Status: Red/Cyan/Pink (avoid blue/yellow confusion)
			bad=					{r=0.902, g=0.102, b=0.102, hex="|cFFE61A1A"},
			good=					{r=0, g=0.8, b=0.702, hex="|cFF00CCB3"},
			warn=					{r=1, g=0.4, b=0.6, hex="|cFFFF6699"},
			auctionhouse=			{r=1, g=0.843, b=0, hex="|cFFFFD700"},

			-- Quest states: red/cyan/pink spectrum
			questCompleted=			{r=0.702, g=0.702, b=0.702, hex="|cFFB3B3B3"},
			questAvailable=			{r=1, g=0.4, b=0.502, hex="|cFFFF6680"},
			questReady=				{r=0, g=0.851, b=0.702, hex="|cFF00D9B3"},
			questReadyBanked=		{r=0.4, g=0.949, b=0.8, hex="|cFF66F2CC"},
			questIgnored=			{r=0.65, g=0.65, b=0.65, hex="|cFFA6A6A6"},
			questPickup=			{r=1.00, g=0.60, b=0.70, hex="|cFFFF99B3"},

			-- Tooltip labels: warm red-pink
			tooltipLeftExp=			{r=1, g=0.302, b=0.4, hex="|cFFFF4D66"},
			tooltipLeftZone=		{r=1, g=0.302, b=0.4, hex="|cFFFF4D66"},
			tooltipLeftCurrentStep= {r=1, g=0.302, b=0.4, hex="|cFFFF4D66"},

			-- Standout text: bright cyan
			standoutText=			{r=0, g=0.902, b=0.8, hex="|cFF00E6CC"},
			manualText=				{r=0.86, g=0.85, b=0.75, hex="|cFFD8D9BF"},

			headerSpecial=			{r=0.40, g=0.35, b=0.72, hex="|cFF6659B7"},
			headerSpecialHover=		{r=0.60, g=0.55, b=0.92, hex="|cFF998CEB"},
			specialSelected=		{r=0.42, g=0.86, b=0.42, hex="|cFF6BDB6B"},
			specialNotSelected=		{r=0.86, g=0.56, b=0.43, hex="|cFFDB8F6B"},

			-- Progress: pink and light
			currentStepProgress=	{r=1, g=0.4, b=0.6, hex="|cFFFF6699"},
			currentStepArea=		{r=0.902, g=0.902, b=0.902, hex="|cFFE6E6E6"},
		}
	},
	["CB_DEUTE_GPT"] = { -- Generated by ChatGPT
		colors = {
			white = 				{r=1, g=1, b=1, hex="|cFFFFFFFF"},
			black = 				{r=0, g=0, b=0, hex="|cFF000000"},

			notifyErrorStart=		{r=0.902, g=0.302, b=0.251, hex="|cFFE64D40"},
			notifyErrorText=		{r=0.902, g=0.302, b=0.251, hex="|cFFE64D40"},
			notifyInfoStart=		{r=0.204, g=0.596, b=0.859, hex="|cFF3498DB"},
			notifyInfoText=			{r=0.204, g=0.596, b=0.859, hex="|cFF3498DB"},

			-- Status: Blue/Yellow/White (avoid red/green confusion)
			bad=					{r=0.902, g=0.302, b=0.251, hex="|cFFE64D40"},
			good=					{r=0.204, g=0.596, b=0.859, hex="|cFF3498DB"},
			warn=					{r=1, g=0.843, b=0, hex="|cFFFFD700"},
			auctionhouse=			{r=1, g=0.843, b=0, hex="|cFFFFD700"},

			-- Quest states: blue/orange spectrum
			questCompleted=			{r=0.584, g=0.647, b=0.651, hex="|cFF95A5A6"},
			questAvailable=			{r=0.902, g=0.486, b=0.133, hex="|cFFE67E22"},
			questReady=				{r=0.204, g=0.596, b=0.859, hex="|cFF3498DB"},
			questReadyBanked=		{r=1, g=0.843, b=0, hex="|cFFFFD700"},
			questIgnored=			{r=0.60, g=0.60, b=0.60, hex="|cFF999999"},
			questPickup=			{r=1.00, g=0.75, b=0.45, hex="|cFFFFBF73"},

			-- Tooltip labels: warm tone
			tooltipLeftExp=			{r=0.953, g=0.612, b=0.071, hex="|cFFF39C12"},
			tooltipLeftZone=		{r=0.953, g=0.612, b=0.071, hex="|cFFF39C12"},
			tooltipLeftCurrentStep= {r=0.953, g=0.612, b=0.071, hex="|cFFF39C12"},

			-- Standout text: cool blue
			standoutText=			{r=0.204, g=0.596, b=0.859, hex="|cFF3498DB"},

			headerSpecial=			{r=0.40, g=0.35, b=0.72, hex="|cFF6659B7"},
			headerSpecialHover=		{r=0.60, g=0.55, b=0.92, hex="|cFF998CEB"},
			specialSelected=		{r=0.42, g=0.86, b=0.42, hex="|cFF6BDB6B"},
			specialNotSelected=		{r=0.86, g=0.56, b=0.43, hex="|cFFDB8F6B"},

			-- Progress: orange and light
			currentStepProgress=	{r=0.902, g=0.486, b=0.133, hex="|cFFE67E22"},
			currentStepArea=		{r=0.925, g=0.941, b=0.945, hex="|cFFECF0F1"},
		}
	},
	["CB_TRITAN_GPT"] = { -- Generated by ChatGPT
		colors = {
			white = 				{r=1, g=1, b=1, hex="|cFFFFFFFF"},
			black = 				{r=0, g=0, b=0, hex="|cFF000000"},

			notifyErrorStart=		{r=0.902, g=0.102, b=0.102, hex="|cFFE61A1A"},
			notifyErrorText=		{r=0.902, g=0.102, b=0.102, hex="|cFFE61A1A"},
			notifyInfoStart=		{r=1, g=0.333, b=0.8, hex="|cFFFF55CC"},
			notifyInfoText=			{r=1, g=0.333, b=0.8, hex="|cFFFF55CC"},

			-- Status: Red/Magenta/Lime (avoid blue/yellow confusion)
			bad=					{r=0.902, g=0.102, b=0.102, hex="|cFFE61A1A"},
			good=					{r=0.333, g=1, b=0.502, hex="|cFF55FF80"},
			warn=					{r=1, g=0.4, b=0.6, hex="|cFFFF6699"},
			auctionhouse=			{r=1, g=0.843, b=0, hex="|cFFFFD700"},

			-- Quest states: red/magenta/lime
			questCompleted=			{r=0.702, g=0.702, b=0.702, hex="|cFFB3B3B3"},
			questAvailable=			{r=1, g=0.4, b=0.6, hex="|cFFFF6699"},
			questReady=				{r=0.333, g=1, b=0.502, hex="|cFF55FF80"},
			questReadyBanked=		{r=0.6, g=1, b=0.8, hex="|cFF99FFCC"},
			questIgnored=			{r=0.55, g=0.55, b=0.55, hex="|cFF8C8C8C"},
			questPickup=			{r=1.00, g=0.55, b=0.80, hex="|cFFFF8CCC"},

			-- Tooltip labels: warm red/pink
			tooltipLeftExp=			{r=1, g=0.302, b=0.4, hex="|cFFFF4D66"},
			tooltipLeftZone=		{r=1, g=0.302, b=0.4, hex="|cFFFF4D66"},
			tooltipLeftCurrentStep= {r=1, g=0.302, b=0.4, hex="|cFFFF4D66"},

			-- Standout text: bright magenta
			standoutText=			{r=1, g=0.333, b=0.8, hex="|cFFFF55CC"},

			headerSpecial=			{r=0.40, g=0.35, b=0.72, hex="|cFF6659B7"},
			headerSpecialHover=		{r=0.60, g=0.55, b=0.92, hex="|cFF998CEB"},
			specialSelected=		{r=0.42, g=0.86, b=0.42, hex="|cFF6BDB6B"},
			specialNotSelected=		{r=0.86, g=0.56, b=0.43, hex="|cFFDB8F6B"},

			-- Progress: pink and light
			currentStepProgress=	{r=1, g=0.4, b=0.6, hex="|cFFFF6699"},
			currentStepArea=		{r=0.902, g=0.902, b=0.902, hex="|cFFE6E6E6"},
		}
	},
}

CasualTBCPrep.Themes.SelectedTheme = themeData[CasualTBCPrep.Themes.DefaultThemeCode]

---@param themeCode string
function CasualTBCPrep.Themes.ChangeTheme(themeCode)
    if themeCode == nil or themeCode == "" then return end
    local theme = themeData[themeCode]
    if theme == nil then return end

    CasualTBCPrep.Themes.SelectedTheme = theme
    CasualTBCPrep.W_Main.ReloadActiveTab()
end

function CasualTBCPrep.Themes.ChangeThemeDefault()
    CasualTBCPrep.Themes.ChangeTheme(CasualTBCPrep.Themes.DefaultThemeCode)
end